[package]
name = "fob-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
fob-core = { workspace = true }
fob-host = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tauri = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true, features = ["codegen"] }
